### PR TITLE
identity_v3 initial implementation

### PR DESCRIPTION
**Pull request by auhlig**
with proper identity v3 objects and working username+password+project-scope,token+project-scope authentication
also comes with test to that

relates to issue: #479 Support for Identity V3

### CODE REVIEW

**Comment by gondor** [comment]
This looks great!  Thanks for the contribution!  Let me know when all code review fixes have been applied to this PR and I'll complete the merge.

**Comment by auhlig** [comment]
closed and reopened PR to trigger travis rebuild.

**Comment by auhlig** [comment]
Got an error:
INFO: Starting server on port 5000
java.net.BindException: Address already in use

There is obviously a server starting before the running one is closed.

I'm going to look into this tomorrow.

**Comment by auhlig** [comment]
Interesting: The naming of the authenticate with token test method caused the error. I renamed it. Looks green again.

**Comment by gondor** [comment]
Awesome, thanks Ando!  Merging into master now

**Pull request merged**
