### PR TITLE
Manila

### PR DESCRIPTION
**Pull request by gondor**

### CODE REVIEW

**Comment by auhlig** [comment]
Note: I started untangling and solving the merge conflicts.

**Comment by gondor** [comment]
@auhlig Thank you.  I started to attempt to on the weekend but got scared I might make a mistake and overwrite something you've changed in V3 since I'm not as familiar with this code base.

**Comment by auhlig** [comment]
@gondor: I manually resolved the merge conflicts caused by the updates. Also added the endpoints for manila and it works fine with Identity V3. 
As I don't dare pushing in the evening I'm going to close this PR and push to the v3_collaboration branch tomorrow morning.

**Comment by gondor** [comment]
@auhlig Awesome! Should we just delete this PR then or was this the one you were using?

**Pull request merged**
