### PR TITLE
A fix regarding connection leak problem #579

### PR DESCRIPTION
**Pull request by dbantchovski**
In case of http call with response, the returned entity should be consumed in order to release the resources associated with the call, and especially the http connection.

I am not sure where is the right place to consume and release the entity. I made a fix for my use-case - create snapshot, but most probably the this fix is applicable for more situations.

### CODE REVIEW

**Comment by gschukin** [comment]
@dbantchovski you mean in httpclient? I've faced something similar developing connector for httpclient5, but since it's not GA didn't take a deep look.

**Comment by gondor** [comment]
Great fix! Thank you

**Comment by dbantchovski** [comment]
@gondor 
Thank you too. I am wondering ... in which version this fix will be included and when it will be released?

**Comment by gondor** [comment]
I'll cut another release this weekend so it will be in 2.20

**Pull request merged**
