### PR TITLE
moved grant/revoke/check-role from user- to role-service

### PR DESCRIPTION
**Pull request by auhlig**
Moved the grant/revoke/check-user-role for domain and project context from the userService to the roleService. That would follow the v2-pattern of where this kind of calls should live.
Any comments by @gondor, @dhague ?

### CODE REVIEW

**Comment by dhague** [comment]
Apart from my comment above (which is not strictly related to this refactoring), LGTM.

**Comment by gondor** [comment]
Outstanding work!  LGTM!

**Comment by auhlig** [comment]
We found a bug in OpenStack that seems to affect every connector except for Jersey2 as described in #530.

But I added failure checks for grant/revoke userrole in domain and project context.

**Comment by dhague** [comment]
Good stuff

**Pull request merged**
