### PR TITLE
upgrade to java 7 and jackson 2.7.3

### PR DESCRIPTION
**Pull request by auhlig**
Upgrade to Java 7 as discussed in #496.

In terms of id v3 I think that is the last thing to include. After that you could trigger the release. 
Makes sense @gondor and @dhague ?

### CODE REVIEW

**Comment by dhague** [comment]
looks good

**Comment by gschukin** [comment]
@auhlig can we have Jackson upgrade to 2.7 for V3? Reference issue #563

**Comment by auhlig** [comment]
@gschukin: Done.

**Comment by gondor** [comment]
LGTM! :)

**Pull request merged**
