### PR TITLE
Orchestration API update

### PR DESCRIPTION
**Pull request by magixyu**
1. StackUpdate supports Environment file and Template file with "get_file"
2. Add findStack API.

### CODE REVIEW

**Comment by magixyu** [comment]
```java
Stack myStack = os.heat().stacks().findStack("mystack");
os.heat().stacks().update("isc02", myStack.getId(), Builders.stackUpdate()
                                          .templateFromFile("template.yaml)
                                          .environmentFromFile("env.yaml")
                                          .timeoutMins(5).build());
```

**Comment by gondor** [comment]
Awesome Thank you!  FYI,  I ended up renaming findStack to be getStackByName.  This follows inline with the current pattern with OpenStack4j when finding some object/entity by it's name.  For example UserServer.getByName("user") is just one example.

**Comment by magixyu** [comment]
That's ok. I use "findStack" just copy from the openstack document :)

**Comment by gondor** [comment]
No problem.  Early on when I first started this project I decided on consistent naming conventions.  Multiple results is always a "list" call and a single result is a "get" variant.  Just makes it nice jumping between the various services as a new user and having common patterns.

**Pull request merged**
