### PR TITLE
Added MAC address to allowe address pair

### PR DESCRIPTION
**Pull request by hyunsun**
There's only IP address now.

### CODE REVIEW

**Comment by gondor** [comment]
Good catch! LGTM thank you!

**Comment by hyunsun** [comment]
Hi gondor, 
Do you know when will the snapshot be updated here https://oss.sonatype.org/content/repositories/snapshots/org/pacesys/?

**Comment by gondor** [comment]
Yep, I'll have it updated in the next few hours.

**Comment by hyunsun** [comment]
Thanks!

**Comment by hyunsun** [comment]
Hi gondor,
I don't want to push you but if you could update the snapshot to sonatype, it would be really helpful for my project.

**Comment by gondor** [comment]
Oh I'm so sorry.  I totally forgot yesterday when I got home. I just deployed the latest snapshot.

**Comment by hyunsun** [comment]
I've just checked it. Thank you so much!

**Pull request merged**
