### PR TITLE
First version of the template and environment file parsing 

### PR DESCRIPTION
**Pull request by magixyu**
It is the first version of the template and environment file parsing. The code won't impact old functionalities.

### CODE REVIEW

**Comment by magixyu** [comment]
os.heat().stacks().create(Builders.stack()
                                          .name("StackName")
                                          .templateFromFile(tplFileLocation)
                                          .environmentFromFile(envFileLocation)
                                          .disableRollback(true)
                                          .timeoutMins(5).build());

**Comment by gondor** [comment]
@magixyu this looks great!  Just got back from holidays! Thanks for the great contribution!!

**Comment by magixyu** [comment]
@gondor Thank you as well. Hope you had a great holiday. I will continue working on this part.

**Comment by gondor** [comment]
I did, we went to Canada to visit family :)  Thanks again for everything!

**Pull request merged**
