### PR TITLE
Manila Shared Filesystems API

### PR DESCRIPTION
**Pull request by gonzolino**
This PR implements the manila API.

### CODE REVIEW

**Comment by gondor** [comment]
@gonzolino Wow, great contribution!  LGTM.    @auhlig Do you mind quickly reviewing to make sure there are no conflicts with the V3 work your doing

**Comment by auhlig** [comment]
Sure. Will do.

**Comment by auhlig** [comment]
From our side this looks good too.

**Comment by gondor** [comment]
Awesome work!

**Comment by gondor** [comment]
@gonzolino Just updated the README.  This contribution brought you up to slot 3 on our Top contributors.  Great work!

**Comment by gonzolino** [comment]
Oh wow! thanks for merging & updating the contributors table.

@auhlig : What exactly has to be done to merge this to the v3_collaboration branch? I think it would be a good idea to also merge this into the v3 branch,. We could work together to make the necessary changes for this to happen.

**Comment by auhlig** [comment]
@gonzolino: I agree. Gondor already created PR #593 to update the v3_collaboration branch. I'll add the manila endpoints to the token catalog when resolving the conflicts on that PR.

**Pull request merged**
