### PR TITLE
Added AlarmService implementation, putSamples(), and files parameter in stack create

### PR DESCRIPTION
**Pull request by maxrome**
Added AlarmService implementation, putSamples(), and files parameter in stack create

### CODE REVIEW

**Comment by maxrome** [comment]
fixed also getstack() using resteasy, now client follows redirects

**Comment by gondor** [comment]
Quick Question, why are methods commented out in like AlarmServiceImpl.java or MeterServiceImpl?

**Comment by maxrome** [comment]
Sorry, I forgot to delete commented methods. I can make a clean of the code and commit it?

**Comment by maxrome** [comment]
Ok, I fixed with commit 9ada17e

**Comment by maxrome** [comment]
Sorry Jeremy, I commited other code today to fix some bugs. Now it should works

Date: Thu, 22 Jan 2015 21:55:55 -0800

**Comment by gondor** [comment]
Thanks you @maxrome

**Comment by e3ky** [comment]
Good work guys!

One question! Is above Alarms enhancement added to:
  <artifactId>openstack4j-core</artifactId>
  <version>2.0.2-SNAPSHOT</version>

I don't see the change in my jar extracted with above rule.

**Comment by maxrome** [comment]
From https://oss.sonatype.org/#nexus-search;gav~org.pacesys~openstack4j~2.0.2-SNAPSHOT~~ I see the last modified date is 22 january, so my commits aren't yet published on oss.sonatype.org repository. You can clone the source and run a mvn install or wait @gondor for publish the new jar

**Comment by e3ky** [comment]
Thank you for the information.
I've went through the code few days ago and didn't notice a way to create Alarms. Is it supported ?

For reference: http://developer.openstack.org/api-ref-telemetry-v2.html

**Pull request merged**
