### PR TITLE
Switch to SLF4J as only logging implementation

### PR DESCRIPTION
**Pull request by gschukin**
This change is not backward compatible with earlier version.

Starting now it is required to specify proper slf4j implementation eg logback or log4j2 otherwise slf4j will fallback to NOP logger

slf4j and log4j plugins also were removed as they are obsolete now

### CODE REVIEW

**Comment by gondor** [comment]
@gschukin Thanks, I'm going to merge this right after this next release.  Could you fix the current conflicts.

**Comment by gschukin** [comment]
@gondor can you please provide the timeframe? 
I'm OOO till mid March and it will take a couple of days to resolve issues.

**Comment by gondor** [comment]
If I release the current snapshot at the end of this week then the next release won't be until after mid march which is when I was going to pull this PR into.  How does that sound @gschukin ?

**Comment by gschukin** [comment]
@gondor I've fixed conflicts. But please do not merge yet, I'll make code review in a couple of days.

Also I'm not sure if everything is OK with OSGi.

**Comment by gondor** [comment]
Awesome, thanks and let me know.  As soon as your ready and we merge I will cut a new release.

**Comment by gschukin** [comment]
@gondor can you plase reciew PR and if OK it's ready to merge

**Comment by gschukin** [comment]
I'm closing this pull request, as it's already committed by @auhlig

**Pull request closed without merging**
